version: "3.7"

services:
  app:
    build:
      context: ./
    image: minicli-php8-dev
    restart: unless-stopped
    working_dir: /home/dan
    volumes:
      - ./:/home/dan
    networks:
      - minicli-dev

networks:
  minicli-dev:
    driver: bridge